"""Report generation tools."""

from google.adk.tools import FunctionTool
import json
from datetime import datetime


def generate_report_markdown(
    title: str,
    summary: str,
    park_analyses: str,
    anomalies: str,
    predictions: str,
    recommendations: str,
) -> str:
    """Generate a structured markdown report from analysis results.

    Args:
        title: Report title
        summary: Executive summary text
        park_analyses: JSON string of park analysis results
        anomalies: JSON string of detected anomalies
        predictions: JSON string of predictions
        recommendations: Bullet-point recommendations

    Returns:
        Complete markdown report string
    """
    report_date = datetime.now().strftime("%Y-%m-%d %H:%M")

    report = f"""# {title}
**Generated:** {report_date}
**System:** PRONUVE Water Intelligence Agent

---

## Executive Summary
{summary}

---

## Park Analysis
{park_analyses}

---

## Anomaly Detection Results
{anomalies}

---

## Consumption Predictions
{predictions}

---

## Recommendations
{recommendations}

---

*This report was automatically generated by PRONUVE Water Intelligence Multi-Agent System.*
*Powered by Google ADK + Gemini on Google Cloud.*
"""

    return json.dumps({"report_markdown": report, "generated_at": report_date})


def export_to_pdf(markdown_content: str, filename: str = "report.pdf") -> str:
    """Export markdown report to PDF (placeholder for Cloud integration).

    Args:
        markdown_content: Markdown text to convert
        filename: Output filename

    Returns:
        Status message with file path
    """
    return json.dumps({
        "success": True,
        "filename": filename,
        "message": f"Report exported to {filename}",
    })


generate_report_markdown = FunctionTool(generate_report_markdown)
export_to_pdf = FunctionTool(export_to_pdf)
